apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-deploy
  name: python-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-deploy
    spec:
      containers:
        - name: python-app # This was missing the name: key
          image: 365591124323.dkr.ecr.us-east-1.amazonaws.com/jayanthroyg/musicshare:v1.5
          imagePullPolicy: Always # This should be indented under the container it belongs to
          resources: {}
status: {}
